# Generated by Django 2.1.2 on 2018-10-30 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='nom')),
                ('resumeCV', models.TextField(verbose_name='Résumé CV')),
            ],
            options={
                'verbose_name': 'Acteur',
            },
        ),
        migrations.CreateModel(
            name='Category_Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=32, unique=True, verbose_name='catégorie')),
            ],
            options={
                'verbose_name': 'catégorie',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=96, unique=True, verbose_name='titre du film')),
                ('synopsis', models.TextField(verbose_name='synopsis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('created_user', models.CharField(max_length=32, verbose_name='utilisateur qui a créé')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='date de modification')),
                ('changed_user', models.CharField(max_length=32, verbose_name='utilisateur qui a modifié')),
                ('picture', models.ImageField(upload_to='', verbose_name='Affiche')),
            ],
            options={
                'verbose_name': 'film',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='nom')),
                ('photo', models.ImageField(upload_to='', verbose_name='Photo')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='nom')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Role',
            },
        ),
        migrations.CreateModel(
            name='Role_Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roledescription', models.CharField(default='', max_length=64, verbose_name='Role Description')),
                ('acteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.Acteur')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.Film')),
            ],
            options={
                'verbose_name': 'film/Acteur/rôle',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='nom')),
                ('UrlVideo', models.URLField(verbose_name='URL de la vidéo')),
            ],
        ),
        migrations.CreateModel(
            name='Video_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='nom')),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='videoType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.Video_Type'),
        ),
        migrations.AddField(
            model_name='film',
            name='Video',
            field=models.ManyToManyField(blank=True, related_name='filmsVideos', to='films.Video'),
        ),
        migrations.AddField(
            model_name='film',
            name='acteur',
            field=models.ManyToManyField(through='films.Role_Film', to='films.Acteur'),
        ),
        migrations.AddField(
            model_name='film',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.Category_Film'),
        ),
        migrations.AddField(
            model_name='film',
            name='photo',
            field=models.ManyToManyField(blank=True, related_name='filmsPhotos', to='films.Photo'),
        ),
    ]
