# Generated by Django 2.1.2 on 2018-10-31 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='acteur',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='Video',
            new_name='video',
        ),
    ]
