# Generated by Django 2.1.2 on 2018-10-31 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_auto_20181031_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='role',
            new_name='acteur_role',
        ),
        migrations.AddField(
            model_name='role_film',
            name='role',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='films.Role'),
        ),
    ]
