# Generated by Django 2.1.2 on 2018-11-07 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_auto_20181031_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre_Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=32, unique=True, verbose_name='genre')),
            ],
            options={
                'verbose_name': 'genre',
            },
        ),
        migrations.RemoveField(
            model_name='film',
            name='category',
        ),
        migrations.AddField(
            model_name='film',
            name='status',
            field=models.CharField(choices=[('ECO', 'En cours'), ('TST', 'Publié Tests'), ('PUB', 'PUblié'), ('ARC', 'Archivé')], default='ECO', max_length=3),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='./films/static/img', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='role_film',
            name='acteur',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='films.Acteur'),
        ),
        migrations.DeleteModel(
            name='Category_Film',
        ),
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='films.Genre_Film'),
        ),
    ]
