# Generated by Django 2.1.2 on 2018-11-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_auto_20181107_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre_film',
            name='genre',
            field=models.CharField(max_length=32, verbose_name='genre'),
        ),
    ]
