# Generated by Django 2.1.2 on 2018-11-07 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_auto_20181107_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.Genre_Film'),
        ),
        migrations.AlterField(
            model_name='genre_film',
            name='genre',
            field=models.CharField(max_length=32, unique=True, verbose_name='genre'),
        ),
    ]
