# Generated by Django 2.1.2 on 2018-11-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_auto_20181107_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='./films/static/film/img', verbose_name='Photo'),
        ),
    ]
