# Generated by Django 2.1.2 on 2018-11-07 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_auto_20181107_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='photo',
            field=models.ManyToManyField(related_name='filmsPhotos', to='films.Photo'),
        ),
        migrations.AlterField(
            model_name='film',
            name='picture',
            field=models.ImageField(upload_to='./films/static/film/img/AffichesFilms', verbose_name='Affiche'),
        ),
        migrations.AlterField(
            model_name='film',
            name='video',
            field=models.ManyToManyField(related_name='filmsVideos', to='films.Video'),
        ),
        migrations.AlterField(
            model_name='role_film',
            name='acteur',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='films.Acteur'),
        ),
        migrations.AlterField(
            model_name='role_film',
            name='role',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='films.Role'),
        ),
        migrations.AlterField(
            model_name='role_film',
            name='roledescription',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Role Description'),
        ),
    ]
