# Generated by Django 2.1.2 on 2018-11-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_auto_20181107_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='acteur',
            name='photoActeur',
            field=models.ImageField(blank=True, upload_to='./films/static/film/img/Photos', verbose_name='Photo Acteur'),
        ),
        migrations.AlterField(
            model_name='film',
            name='status',
            field=models.CharField(choices=[('ECO', 'En cours'), ('TST', 'Publié Tests'), ('PUB', 'Publié'), ('ARC', 'Archivé')], default='ECO', max_length=3),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='./films/static/film/img/Photos', verbose_name='Photo'),
        ),
    ]
