# Generated by Django 2.1.2 on 2018-11-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_auto_20181107_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='an_creation',
            field=models.IntegerField(blank=True, default=2018, max_length=4, verbose_name='Année'),
        ),
    ]
