# Generated by Django 2.1.2 on 2018-11-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0010_film_an_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acteur',
            name='photoActeur',
            field=models.ImageField(blank=True, upload_to='../static/film/img/Photos', verbose_name='Photo Acteur'),
        ),
        migrations.AlterField(
            model_name='film',
            name='an_creation',
            field=models.IntegerField(blank=True, default=2018, verbose_name='Année Création'),
        ),
        migrations.AlterField(
            model_name='film',
            name='picture',
            field=models.ImageField(upload_to='../static/film/img/AffichesFilms', verbose_name='Affiche'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='../static/film/img/Photos', verbose_name='Photo'),
        ),
    ]
