# Generated by Django 2.1.2 on 2018-11-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0012_auto_20181107_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acteur',
            name='photoActeur',
            field=models.ImageField(blank=True, upload_to='../Images/Photos', verbose_name='Photo Acteur'),
        ),
        migrations.AlterField(
            model_name='film',
            name='picture',
            field=models.ImageField(upload_to='../Images/AffichesFilms', verbose_name='Affiche'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='../Images/Photos', verbose_name='Photo'),
        ),
    ]
