# Generated by Django 2.1.3 on 2018-11-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0015_auto_20181114_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='UrlVideo',
            field=models.CharField(blank=True, max_length=20, verbose_name='URL de la vidéo'),
        ),
    ]
