# Generated by Django 2.1.4 on 2018-12-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0016_auto_20181116_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Votre prénom')),
                ('name', models.CharField(max_length=100, verbose_name='Votre nom')),
                ('email_address', models.EmailField(max_length=254, verbose_name='Votre adresse email')),
                ('subject', models.CharField(max_length=100, verbose_name='Objet de votre messsage')),
                ('message', models.TextField(verbose_name='Texte de votre message')),
            ],
            options={
                'verbose_name': 'Contact',
            },
        ),
    ]
