# Generated by Django 2.1.5 on 2019-01-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0017_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='an_creation',
            field=models.IntegerField(blank=True, default=2019, verbose_name='Année Création'),
        ),
    ]
