# Generated by Django 2.1.5 on 2019-02-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0018_auto_20190111_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role_film',
            options={'verbose_name': 'Rôles des participants dans film'},
        ),
        migrations.AlterField(
            model_name='acteur',
            name='photoActeur',
            field=models.ImageField(blank=True, upload_to='images/Photos/', verbose_name='Photo Acteur'),
        ),
        migrations.AlterField(
            model_name='acteur',
            name='resumeCV',
            field=models.TextField(blank=True, verbose_name='Résumé CV'),
        ),
        migrations.AlterField(
            model_name='film',
            name='picture',
            field=models.ImageField(upload_to='images/AffichesFilms/', verbose_name='Affiche'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='images/Photos/', verbose_name='Photo'),
        ),
    ]
