# Generated by Django 2.1.5 on 2019-02-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181206_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='images/PhotosBlog/', verbose_name='Photo'),
        ),
    ]
